network:
  version: 2
  ethernets:
    enp6s18:
      match:
        macaddress: bc:24:11:4b:0f:c5
      addresses:
        - 10.44.0.101/24
      routes:
        - to: default
          via : 10.44.0.1
